### ISSUE TITLE
本地启动报错，疑似mysql driver未加载完成，就获取连接

### ISSUE THREAD

**Issue by hanglegehang** [xyhelper/chatgpt-share-server#12]
API server listening at: 127.0.0.1:57021
debugserver-@(#)PROGRAM:LLDB  PROJECT:lldb-1500.0.200.58
 for arm64.
Got a connection, launched process /Users/lihang15/Library/Caches/JetBrains/IntelliJIdea2023.3/tmp/GoLand/___3go_build_backend (pid = 42771).
WARNING: undefined behavior - version of Delve is too old for Go version go1.22.0 (maximum supported version 1.21)
2024-03-08 01:46:52.077 [INFO] {50797a709c8cba17c79ed6289bcc2a26} CHATPROXY: https://demo.xyhelper.cn
2024-03-08 01:46:52.078 [INFO] {50797a709c8cba17c79ed6289bcc2a26} AUTHKEY: xyhelper
2024-03-08 01:46:52.078 [INFO] {50797a709c8cba17c79ed6289bcc2a26} ASSET_PREFIX: https://oaistatic-cdn.closeai.biz
2024-03-08 01:46:52.752 [INFO] {50797a709c8cba17c79ed6289bcc2a26} Get config From https://oaistatic-cdn.closeai.biz ,CacheBuildId: CdVKBysnaJNkqh_-wcfYZ
2024-03-08 01:46:52.753 [INFO] {50797a709c8cba17c79ed6289bcc2a26} Get config From  https://oaistatic-cdn.closeai.biz/template/CdVKBysnaJNkqh_-wcfYZ/index.txt
2024-03-08 01:46:53.420 [INFO] {50797a709c8cba17c79ed6289bcc2a26} CacheBuildId: CdVKBysnaJNkqh_-wcfYZ
2024-03-08 01:46:54.155 [INFO] {50797a709c8cba17c79ed6289bcc2a26} BuildId: uFQkCP-fqpvXX_WWG3TaH
2024-03-08 01:46:54.155 [INFO] {50797a709c8cba17c79ed6289bcc2a26} PORT: 8001
2024-03-08 01:46:54.162 [DEBU] SetServerRoot path: /Users/lihang15/IdeaProjects/chatgpt-share-server/backend/resource/public
2024-03-08 01:46:54.162 [INFO] {50797a709c8cba17c79ed6289bcc2a26} OAUTH_URL: http://127.0.0.1:8001/auth/oauthfree
2024-03-08 01:46:54.162 [INFO] {50797a709c8cba17c79ed6289bcc2a26} AUDIT_LIMIT_URL:
2024-03-08 01:46:54.162 [INFO] {50797a709c8cba17c79ed6289bcc2a26} APIAUTH:
2024-03-08 01:46:54.163 [DEBU] {50797a709c8cba17c79ed6289bcc2a26} module cool init start ...
2024-03-08 01:46:54.163 [DEBU] {50797a709c8cba17c79ed6289bcc2a26} 当前运行模式 dev
2024-03-08 01:46:54.164 [DEBU] {50797a709c8cba17c79ed6289bcc2a26} 当前实例ID: 1mknz3bx030cznpfikt0vx4100dp0zln
2024-03-08 01:46:54.164 [DEBU] {50797a709c8cba17c79ed6289bcc2a26} 是否缓存模式: true
2024-03-08 01:46:54.164 [DEBU] {50797a709c8cba17c79ed6289bcc2a26} module cool init finished ...
panic: cannot find database driver for specified database type "mysql", did you misspell type name "mysql" or forget importing the database driver? possible reference: https://github.com/gogf/gf/tree/master/contrib/drivers [recovered]
        panic: failed to connect database

goroutine 1 [running]:
github.com/cool-team-official/cool-admin-go/cool.InitDB.func1()
        /Users/lihang15/go/pkg/mod/github.com/cool-team-official/cool-admin-go/cool@v1.5.10/initdb.go:21 +0x54
panic({0x10546b320?, 0x14000282690?})
        /usr/local/go/src/runtime/panic.go:770 +0xf0
github.com/gogf/gf/v2/frame/gins.Database.func1()
        /Users/lihang15/go/pkg/mod/github.com/gogf/gf/v2@v2.6.3/frame/gins/gins_database.go:148 +0xfd0
github.com/gogf/gf/v2/container/gmap.(*StrAnyMap).doSetWithLockCheck(0x1400011f780, {0x14000039890, 0x22}, {0x105370000, 0x14000280740})
        /Users/lihang15/go/pkg/mod/github.com/gogf/gf/v2@v2.6.3/container/gmap/gmap_hash_str_any_map.go:219 +0x220
github.com/gogf/gf/v2/container/gmap.(*StrAnyMap).GetOrSetFuncLock(0x1400011f780, {0x14000039890, 0x22}, 0x14000280740)
        /Users/lihang15/go/pkg/mod/github.com/gogf/gf/v2@v2.6.3/container/gmap/gmap_hash_str_any_map.go:256 +0xbc
github.com/gogf/gf/v2/internal/instance.GetOrSetFuncLock({0x14000039890, 0x22}, 0x14000280740)
        /Users/lihang15/go/pkg/mod/github.com/gogf/gf/v2@v2.6.3/internal/instance/instance.go:65 +0x48
github.com/gogf/gf/v2/frame/gins.Database({0x14000530930, 0x1, 0x1})
        /Users/lihang15/go/pkg/mod/github.com/gogf/gf/v2@v2.6.3/frame/gins/gins_database.go:37 +0x29c
github.com/gogf/gf/v2/frame/g.DB({0x14000530930, 0x1, 0x1})
        /Users/lihang15/go/pkg/mod/github.com/gogf/gf/v2@v2.6.3/frame/g/g_object.go:87 +0x38
github.com/cool-team-official/cool-admin-go/cool.InitDB({0x10518eba0, 0x7})
        /Users/lihang15/go/pkg/mod/github.com/cool-team-official/cool-admin-go/cool@v1.5.10/initdb.go:24 +0xe8
github.com/cool-team-official/cool-admin-go/cool.getDBbyModel({0x1054f10a0, 0x140007ae4e0})
        /Users/lihang15/go/pkg/mod/github.com/cool-team-official/cool-admin-go/cool@v1.5.10/initdb.go:43 +0xd4
github.com/cool-team-official/cool-admin-go/cool.CreateTable({0x1054f10a0, 0x140007ae4e0})
        /Users/lihang15/go/pkg/mod/github.com/cool-team-official/cool-admin-go/cool@v1.5.10/initdb.go:56 +0x4c
backend/modules/chatgpt/model.init.0()
        /Users/lihang15/IdeaProjects/chatgpt-share-server/backend/modules/chatgpt/model/chatgpt_conversations.go:39 +0x88
Exiting.

Debugger finished with the exit code 0

**Comment by hanglegehang** [comment]
go版本降到1.20.6解决

**Comment by hanglegehang** [comment]
https://tonybai.com/2023/08/20/some-changes-in-go-1-21/
破案了 1.21更新包导入算法
